config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  attr_accessor :remember_token

  before_save :downcase_email

  validates :name, presence: true, length: {maximum: Settings.user.max_name_length}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: Settings.user.max_email_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: Settings.user.min_password_length},
    allow_nil: true

  has_secure_password

  scope :id_sort, ->{order id: :asc}
  scope :search_user, ->keywords{where "name LIKE ?", "%#{keywords}%"}

  class << self
    def digest string
      if ActiveModel::SecurePassword.min_cost
        cost = BCrypt::Engine::MIN_COST
      else
        cost = BCrypt::Engine.cost
      end

      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    return false unless remember_token
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
      WHERE follower_id = :user_id"
    Micropost.load_feed id, following_ids
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:new, :create, :index]
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :verify_admin, only: :destroy
  before_action :correct_user, only: [:edit, :update]

  def index
    if params[:search]
      @users = User.search_user params[:name]
      render json: {
        html_search: render_to_string(@users, layout: false)
      }
    end

    @users = User.select(:id, :name, :email).id_sort
      .paginate page: params[:page], per_page: Settings.user.per_page
  end

  def show
    @microposts = @user.microposts
      .select(:id, :content, :user_id, :created_at, :title, :picture).micropost_sort
      .paginate page: params[:page], per_page: Settings.micropost.post_per_page
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      log_in @user
      flash[:success] = t ".success"
      redirect_to @user
    else
      flash.now[:danger] = t ".fail"
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".updated"
      redirect_to @user
    else
      flash.now[:danger] = t ".fail_update"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t ".deleted"
    else
      flash[:danger] = t ".fail_delete"
    end
    redirect_to users_url
  end

  def following
    @title = t ".following"
    @users = @user.following.select(:id, :email, :name).id_sort
      .paginate page: params[:page], per_page: Settings.user.per_page
    render :show_follow
  end

  def followers
    @title = t ".followers"
    @users = @user.followers.select(:id, :email, :name).id_sort
      .paginate page: params[:page], per_page: Settings.user.per_page
    render :show_follow
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    valid_info @user
  end

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end

  def correct_user
    @user = User.find_by id: params[:id]
    redirect_to root_url unless current_user? @user
  end

  def verify_admin
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: Settings.helpers.max_size}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t(".follow"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user? @user %>
  <div class="follow_form">
    <% if current_user.following? @user %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, url: yield(:url) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, t(".mail") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, t(".pass") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t(".confirm") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
  html: {method: :delete}, remote: true do |f| %>
  <%= f.submit t(".unfollow"), class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.users_form.size %>
  <%= link_to user.name, user %>
  <% if current_user && current_user.admin? && !current_user?(user) %>
    <%= link_to t(".delete"), user, method: :delete, data: {confirm: t(".sure")} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".edit") %>
<%= provide :button_text, t(".edit_info") %>
<%= provide :url, user_path %>

<h1><%= t ".edit" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank"><%= t ".change" %></a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".all") %>
<h1><%= t ".all" %></h1>

<div class="search-result">
  <%= form_for :search do |f| %>
    <%= f.text_field :search_key, remote: true, class: "form-control search_box" %>
  <% end %>

  <ul class="search-area">
  </ul>
</div>

<%= will_paginate %>

<ul class="users-list">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t(".sign") %>
<%= provide :button_text, t(".create") %>
<%= provide :url, signup_path %>

<h1><%= t ".sign" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <span class="join-date">
        <%= t ".joined" %>: <%= @user.created_at.strftime "%d/%m/%Y" %>
      </span>
      <span class="join-date">
        <%= t ".post" %>: <%= @user.microposts.size %>
      </span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render "follow_form" if logged_in? %>
    <% if @user.microposts.any? %>
      <h3><%= t ".microposts" %> (<%= @user.microposts.size %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide :title, @title %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to t(".profile"), @user %></span>
      <span><b><%= t ".post" %>:</b> <%= @user.microposts.size %></span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
      <% if @users.any? %>
        <div class="user-avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users-list follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>