config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: :new do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:show, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".the" %> <%= link_to t(".tutu"), "http://www.railstutorial.org" %>
    <%= t ".by" %> <%= link_to t(".hartl"), "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".news"), "http://www.railstutorial.org" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("rails.png"), root_path, class: "logo-img" %>
    <input type="checkbox" id="menuTrigger"/>
    <div class="menu">
      <% if logged_in? %>
        <h3><%= link_to current_user.name, "#", id: "logo" %></h3>
      <% else %>
        <h3><%= link_to t(".sample"), root_path, id: "logo" %></h3>
      <% end %>
      <label for="menuTrigger" class="trigger">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
      </label>
      <ul class="links">
        <li class="link"><%= link_to t(".home"), root_path %></li>
        <li class="link"><%= link_to t(".help"), help_path %></li>
        <li class="link"><%= link_to t(".users"), users_path %></li>
        <% if logged_in? %>
          <li class="link"><%= link_to t(".profile"), current_user %></li>
          <li class="link"><%= link_to t(".setting"), edit_user_path(current_user) %></li>
          <li class="link"><%= link_to t(".logout"), logout_path, method: :delete %></li>
        <% else %>
          <li class="link"><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>